### PR TITLE
Entity relationship diagram, adding to readme

### PR DESCRIPTION
**Pull request by jacindaz**

### CODE REVIEW

**Comment by jacindaz** [comment]
Oh yea! Whoopsies, forgot about that. Hmm, then maybe classes should be changed to something else? I can't decide if it should be something more abstract like `events`, or just have classes be separate from attending a social dance.

**Comment by jacindaz** [comment]
Oh also, I will add a column for the date of the `class/event/whatever-we-call-it`, since we want to track attendance!.

**Comment by kwl** [comment]
The diagram is cool! There are a couple additional fields on (new) dancers that are part of the registration form now, like whether they're getting the student or new dancer discount. Not sure if payment-related info should be part of the user data.

**Comment by jacindaz** [comment]
Oh! I didn't realize there was a new registration form. Definitely should incorporate those somewhere! @lunaruan Do you think you could email or fb messenger us that new reg form? <3

**Comment by missmaggiemo** [comment]
I'm just going to close this PR as it's not relevant to what ended up being built. `¯\_(ツ)_/¯`

**Pull request closed without merging**
